---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 66c322200872f32b81d42cede516228a707ea5c7
    app.quarkus.io/build-timestamp: 2022-11-08 - 10:16:46 +0000
  labels:
    app.kubernetes.io/name: primer-leocloud
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: primer-leocloud
  namespace: student-d-thaller
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: primer-leocloud
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 66c322200872f32b81d42cede516228a707ea5c7
    app.quarkus.io/build-timestamp: 2022-11-08 - 10:16:46 +0000
  labels:
    app.kubernetes.io/name: primer-leocloud
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: primer-leocloud
  namespace: student-d-thaller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: primer-leocloud
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 66c322200872f32b81d42cede516228a707ea5c7
        app.quarkus.io/build-timestamp: 2022-11-08 - 10:16:46 +0000
      labels:
        app.kubernetes.io/name: primer-leocloud
        app.kubernetes.io/version: 1.0-SNAPSHOT
      namespace: student-d-thaller
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/thallerdavid/primer-leocloud:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: primer-leocloud
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
